# -*- coding: utf-8 -*-
"""qiskit_to_stim.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1beWg2pyn_TzEPzo-3kd6Ig59zA_kqnpM
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install qiskit
# !pip install stim

from qiskit import QuantumCircuit
import stim

def qiskit_to_stim(qc: QuantumCircuit) -> stim.Circuit:
    stim_circuit = stim.Circuit()

    # Map Qiskit gate names to Stim gate names
    gate_map = {
        'h': 'H', 'x': 'X', 'y': 'Y', 'z': 'Z',
        's': 'S', 'sdg': 'S_DAG',
        'cx': 'CNOT', 'cz': 'CZ', 'swap': 'SWAP',
        'reset': 'R', 'measure': 'M'
    }

    for instruction in qc.data:
        gate_name = instruction.operation.name

        # Skip barriers and delays as Stim doesn't need them
        if gate_name in ['barrier', 'delay']:
            continue

        if gate_name not in gate_map:
            raise ValueError(f"Gate '{gate_name}' is not supported by Stim.")

        # Extract integer qubit indices
        qubits = [qc.find_bit(q).index for q in instruction.qubits]

        # Append to Stim circuit
        stim_circuit.append(gate_map[gate_name], qubits)

    return stim_circuit


def transpile_to_stim_with_detectors(qc: QuantumCircuit, syndrome_cbits: list):
    stim_circ = stim.Circuit()

    # 1. Map physical Qubit objects to integer indices for Stim
    qubit_map = {q: i for i, q in enumerate(qc.qubits)}

    # 2. Track the absolute index of every measurement appended to Stim
    total_measurements = 0

    # Maps a Qiskit Clbit object to its absolute measurement index
    cbit_history = {}

    for instruction in qc.data:
        gate = instruction.operation.name
        qargs = [qubit_map[q] for q in instruction.qubits]

        # Translate standard Clifford operations
        if gate in ['h', 'x', 'y', 'z', 's']:
            stim_circ.append(gate.upper(), qargs)
        elif gate == 'cx':
            stim_circ.append("CX", qargs)
        elif gate == 'cz':
            stim_circ.append("CZ", qargs)

        # Handle measurements and Detector injection
        elif gate == 'measure':
            stim_circ.append("M", qargs)

            cbit = instruction.clbits[0]

            # If this syndrome was measured previously, inject a detector
            if cbit in cbit_history and cbit in syndrome_cbits:
                prev_meas_idx = cbit_history[cbit]

                # Stim targets are relative to the total number of measurements
                # currently existing in the circuit.
                # The measurement we just appended is at offset -1.
                record_target_current = stim.target_rec(-1)

                # Calculate how far back the previous measurement of this bit is.
                # Because total_measurements hasn't been incremented for the current one yet,
                # we add 1 to the total to represent the state *after* this instruction.
                offset = prev_meas_idx - (total_measurements + 1)
                record_target_prev = stim.target_rec(offset)

                # Append the detector comparing this round to the previous round
                stim_circ.append("DETECTOR", [record_target_prev, record_target_current])

            # Update history and increment counter
            cbit_history[cbit] = total_measurements
            total_measurements += 1

        elif gate == 'barrier':
            stim_circ.append("TICK")

    return stim_circ